# Generated by Django 2.1.7 on 2019-07-25 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doc',
            options={'verbose_name': '文档', 'verbose_name_plural': '文档'},
        ),
    ]
