# Generated by Django 2.1.7 on 2019-07-25 04:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_comments_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='digest',
            field=models.CharField(help_text='摘要', max_length=200, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(help_text='标题', max_length=150, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='标题'),
        ),
    ]
